'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WS
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WS.WSCRUDSoap")>  _
    Public Interface WSCRUDSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EntradaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Entrada", ReplyAction:="*")>  _
        Function Entrada(ByVal request As WS.EntradaRequest) As WS.EntradaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Entrada", ReplyAction:="*")>  _
        Function EntradaAsync(ByVal request As WS.EntradaRequest) As System.Threading.Tasks.Task(Of WS.EntradaResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SalidaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Salida", ReplyAction:="*")>  _
        Function Salida(ByVal request As WS.SalidaRequest) As WS.SalidaResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Salida", ReplyAction:="*")>  _
        Function SalidaAsync(ByVal request As WS.SalidaRequest) As System.Threading.Tasks.Task(Of WS.SalidaResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/registar", ReplyAction:="*")>  _
        Function registar(ByVal request As WS.registarRequest) As WS.registarResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/registar", ReplyAction:="*")>  _
        Function registarAsync(ByVal request As WS.registarRequest) As System.Threading.Tasks.Task(Of WS.registarResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updatesql", ReplyAction:="*")>  _
        Function updatesql(ByVal request As WS.updatesqlRequest) As WS.updatesqlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updatesql", ReplyAction:="*")>  _
        Function updatesqlAsync(ByVal request As WS.updatesqlRequest) As System.Threading.Tasks.Task(Of WS.updatesqlResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DeletedatosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Deletedatos", ReplyAction:="*")>  _
        Function Deletedatos(ByVal request As WS.DeletedatosRequest) As WS.DeletedatosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Deletedatos", ReplyAction:="*")>  _
        Function DeletedatosAsync(ByVal request As WS.DeletedatosRequest) As System.Threading.Tasks.Task(Of WS.DeletedatosResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EntradaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Entrada", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.EntradaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.EntradaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EntradaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Matricula As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Matricula As Integer)
            MyBase.New
            Me.Matricula = Matricula
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EntradaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EntradaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.EntradaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.EntradaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EntradaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EntradaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EntradaResult As String)
            MyBase.New
            Me.EntradaResult = EntradaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalidaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Salida", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.SalidaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.SalidaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SalidaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Matricula As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Matricula As Integer)
            MyBase.New
            Me.Matricula = Matricula
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SalidaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SalidaResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.SalidaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.SalidaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SalidaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public SalidaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SalidaResult As String)
            MyBase.New
            Me.SalidaResult = SalidaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class registarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="registar", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.registarRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.registarRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class registarRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public matricula As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public nombre As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public apaterno As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public amaterno As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public carrera As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public cuatri As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public finicio As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public ffin As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal matricula As Integer, ByVal nombre As String, ByVal apaterno As String, ByVal amaterno As String, ByVal carrera As Integer, ByVal cuatri As Integer, ByVal finicio As String, ByVal ffin As String)
            MyBase.New
            Me.matricula = matricula
            Me.nombre = nombre
            Me.apaterno = apaterno
            Me.amaterno = amaterno
            Me.carrera = carrera
            Me.cuatri = cuatri
            Me.finicio = finicio
            Me.ffin = ffin
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class registarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="registarResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.registarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.registarResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class registarResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public registarResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal registarResult As String)
            MyBase.New
            Me.registarResult = registarResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updatesqlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updatesql", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.updatesqlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.updatesqlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updatesqlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public nombre As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public apaterno As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public amaterno As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public carrera As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public cuatri As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public finicio As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public ffin As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public matricula As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal nombre As String, ByVal apaterno As String, ByVal amaterno As String, ByVal carrera As Integer, ByVal cuatri As Integer, ByVal finicio As String, ByVal ffin As String, ByVal matricula As Integer)
            MyBase.New
            Me.nombre = nombre
            Me.apaterno = apaterno
            Me.amaterno = amaterno
            Me.carrera = carrera
            Me.cuatri = cuatri
            Me.finicio = finicio
            Me.ffin = ffin
            Me.matricula = matricula
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updatesqlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updatesqlResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.updatesqlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.updatesqlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updatesqlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public updatesqlResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updatesqlResult As String)
            MyBase.New
            Me.updatesqlResult = updatesqlResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeletedatosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Deletedatos", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.DeletedatosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.DeletedatosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DeletedatosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public matricula As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal matricula As Integer)
            MyBase.New
            Me.matricula = matricula
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DeletedatosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeletedatosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS.DeletedatosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS.DeletedatosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DeletedatosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DeletedatosResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DeletedatosResult As String)
            MyBase.New
            Me.DeletedatosResult = DeletedatosResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WSCRUDSoapChannel
        Inherits WS.WSCRUDSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSCRUDSoapClient
        Inherits System.ServiceModel.ClientBase(Of WS.WSCRUDSoap)
        Implements WS.WSCRUDSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_Entrada(ByVal request As WS.EntradaRequest) As WS.EntradaResponse Implements WS.WSCRUDSoap.Entrada
            Return MyBase.Channel.Entrada(request)
        End Function
        
        Public Function Entrada(ByVal Matricula As Integer) As String
            Dim inValue As WS.EntradaRequest = New WS.EntradaRequest()
            inValue.Body = New WS.EntradaRequestBody()
            inValue.Body.Matricula = Matricula
            Dim retVal As WS.EntradaResponse = CType(Me,WS.WSCRUDSoap).Entrada(inValue)
            Return retVal.Body.EntradaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_EntradaAsync(ByVal request As WS.EntradaRequest) As System.Threading.Tasks.Task(Of WS.EntradaResponse) Implements WS.WSCRUDSoap.EntradaAsync
            Return MyBase.Channel.EntradaAsync(request)
        End Function
        
        Public Function EntradaAsync(ByVal Matricula As Integer) As System.Threading.Tasks.Task(Of WS.EntradaResponse)
            Dim inValue As WS.EntradaRequest = New WS.EntradaRequest()
            inValue.Body = New WS.EntradaRequestBody()
            inValue.Body.Matricula = Matricula
            Return CType(Me,WS.WSCRUDSoap).EntradaAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_Salida(ByVal request As WS.SalidaRequest) As WS.SalidaResponse Implements WS.WSCRUDSoap.Salida
            Return MyBase.Channel.Salida(request)
        End Function
        
        Public Function Salida(ByVal Matricula As Integer) As String
            Dim inValue As WS.SalidaRequest = New WS.SalidaRequest()
            inValue.Body = New WS.SalidaRequestBody()
            inValue.Body.Matricula = Matricula
            Dim retVal As WS.SalidaResponse = CType(Me,WS.WSCRUDSoap).Salida(inValue)
            Return retVal.Body.SalidaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_SalidaAsync(ByVal request As WS.SalidaRequest) As System.Threading.Tasks.Task(Of WS.SalidaResponse) Implements WS.WSCRUDSoap.SalidaAsync
            Return MyBase.Channel.SalidaAsync(request)
        End Function
        
        Public Function SalidaAsync(ByVal Matricula As Integer) As System.Threading.Tasks.Task(Of WS.SalidaResponse)
            Dim inValue As WS.SalidaRequest = New WS.SalidaRequest()
            inValue.Body = New WS.SalidaRequestBody()
            inValue.Body.Matricula = Matricula
            Return CType(Me,WS.WSCRUDSoap).SalidaAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_registar(ByVal request As WS.registarRequest) As WS.registarResponse Implements WS.WSCRUDSoap.registar
            Return MyBase.Channel.registar(request)
        End Function
        
        Public Function registar(ByVal matricula As Integer, ByVal nombre As String, ByVal apaterno As String, ByVal amaterno As String, ByVal carrera As Integer, ByVal cuatri As Integer, ByVal finicio As String, ByVal ffin As String) As String
            Dim inValue As WS.registarRequest = New WS.registarRequest()
            inValue.Body = New WS.registarRequestBody()
            inValue.Body.matricula = matricula
            inValue.Body.nombre = nombre
            inValue.Body.apaterno = apaterno
            inValue.Body.amaterno = amaterno
            inValue.Body.carrera = carrera
            inValue.Body.cuatri = cuatri
            inValue.Body.finicio = finicio
            inValue.Body.ffin = ffin
            Dim retVal As WS.registarResponse = CType(Me,WS.WSCRUDSoap).registar(inValue)
            Return retVal.Body.registarResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_registarAsync(ByVal request As WS.registarRequest) As System.Threading.Tasks.Task(Of WS.registarResponse) Implements WS.WSCRUDSoap.registarAsync
            Return MyBase.Channel.registarAsync(request)
        End Function
        
        Public Function registarAsync(ByVal matricula As Integer, ByVal nombre As String, ByVal apaterno As String, ByVal amaterno As String, ByVal carrera As Integer, ByVal cuatri As Integer, ByVal finicio As String, ByVal ffin As String) As System.Threading.Tasks.Task(Of WS.registarResponse)
            Dim inValue As WS.registarRequest = New WS.registarRequest()
            inValue.Body = New WS.registarRequestBody()
            inValue.Body.matricula = matricula
            inValue.Body.nombre = nombre
            inValue.Body.apaterno = apaterno
            inValue.Body.amaterno = amaterno
            inValue.Body.carrera = carrera
            inValue.Body.cuatri = cuatri
            inValue.Body.finicio = finicio
            inValue.Body.ffin = ffin
            Return CType(Me,WS.WSCRUDSoap).registarAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_updatesql(ByVal request As WS.updatesqlRequest) As WS.updatesqlResponse Implements WS.WSCRUDSoap.updatesql
            Return MyBase.Channel.updatesql(request)
        End Function
        
        Public Function updatesql(ByVal nombre As String, ByVal apaterno As String, ByVal amaterno As String, ByVal carrera As Integer, ByVal cuatri As Integer, ByVal finicio As String, ByVal ffin As String, ByVal matricula As Integer) As String
            Dim inValue As WS.updatesqlRequest = New WS.updatesqlRequest()
            inValue.Body = New WS.updatesqlRequestBody()
            inValue.Body.nombre = nombre
            inValue.Body.apaterno = apaterno
            inValue.Body.amaterno = amaterno
            inValue.Body.carrera = carrera
            inValue.Body.cuatri = cuatri
            inValue.Body.finicio = finicio
            inValue.Body.ffin = ffin
            inValue.Body.matricula = matricula
            Dim retVal As WS.updatesqlResponse = CType(Me,WS.WSCRUDSoap).updatesql(inValue)
            Return retVal.Body.updatesqlResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_updatesqlAsync(ByVal request As WS.updatesqlRequest) As System.Threading.Tasks.Task(Of WS.updatesqlResponse) Implements WS.WSCRUDSoap.updatesqlAsync
            Return MyBase.Channel.updatesqlAsync(request)
        End Function
        
        Public Function updatesqlAsync(ByVal nombre As String, ByVal apaterno As String, ByVal amaterno As String, ByVal carrera As Integer, ByVal cuatri As Integer, ByVal finicio As String, ByVal ffin As String, ByVal matricula As Integer) As System.Threading.Tasks.Task(Of WS.updatesqlResponse)
            Dim inValue As WS.updatesqlRequest = New WS.updatesqlRequest()
            inValue.Body = New WS.updatesqlRequestBody()
            inValue.Body.nombre = nombre
            inValue.Body.apaterno = apaterno
            inValue.Body.amaterno = amaterno
            inValue.Body.carrera = carrera
            inValue.Body.cuatri = cuatri
            inValue.Body.finicio = finicio
            inValue.Body.ffin = ffin
            inValue.Body.matricula = matricula
            Return CType(Me,WS.WSCRUDSoap).updatesqlAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_Deletedatos(ByVal request As WS.DeletedatosRequest) As WS.DeletedatosResponse Implements WS.WSCRUDSoap.Deletedatos
            Return MyBase.Channel.Deletedatos(request)
        End Function
        
        Public Function Deletedatos(ByVal matricula As Integer) As String
            Dim inValue As WS.DeletedatosRequest = New WS.DeletedatosRequest()
            inValue.Body = New WS.DeletedatosRequestBody()
            inValue.Body.matricula = matricula
            Dim retVal As WS.DeletedatosResponse = CType(Me,WS.WSCRUDSoap).Deletedatos(inValue)
            Return retVal.Body.DeletedatosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_WSCRUDSoap_DeletedatosAsync(ByVal request As WS.DeletedatosRequest) As System.Threading.Tasks.Task(Of WS.DeletedatosResponse) Implements WS.WSCRUDSoap.DeletedatosAsync
            Return MyBase.Channel.DeletedatosAsync(request)
        End Function
        
        Public Function DeletedatosAsync(ByVal matricula As Integer) As System.Threading.Tasks.Task(Of WS.DeletedatosResponse)
            Dim inValue As WS.DeletedatosRequest = New WS.DeletedatosRequest()
            inValue.Body = New WS.DeletedatosRequestBody()
            inValue.Body.matricula = matricula
            Return CType(Me,WS.WSCRUDSoap).DeletedatosAsync(inValue)
        End Function
    End Class
End Namespace
